/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antrianloket;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sigma
 */
public class KioskForm2 extends javax.swing.JFrame {

    /**
     * Creates new form KioskForm
     */
    public static DatagramSocket serversocket;
    public static DatagramPacket dp;
    public static BufferedReader dis;
    public static InetAddress ia;
    public static byte buf[] = new byte[1024];
    public static int cport = 789, sport = 790;
    
    public ArrayList<String> antrianAdmin = new ArrayList<String>();
    public ArrayList<String> antrianTeller = new ArrayList<String>();
    public ArrayList<String> antrianCs = new ArrayList<String>();
    
    public int nomorAntrianAdmin =0;
    public int nomorAntrianTeller =0;
    public int nomorAntrianCs =0;
    
    
    
    public KioskForm2() {
        try {
            initComponents();
            try {
                serversocket = new DatagramSocket(sport);
            } catch (SocketException ex) {
                Logger.getLogger(KioskForm2.class.getName()).log(Level.SEVERE, null, ex);
            }
            dp = new DatagramPacket(buf, buf.length);
            dis = new BufferedReader(new InputStreamReader(System.in));
            ia = InetAddress.getLocalHost();
            
        } catch (UnknownHostException ex) {
            Logger.getLogger(KioskForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void sendRequest(String type) throws SocketException, UnknownHostException, IOException{
        String str=" ";
        System.out.println("tess");
        
        if (type.equals("admin")) {
            nomorAntrianAdmin++;
            str = "A"+nomorAntrianAdmin;
        }else if (type.equals("teller")) {
            nomorAntrianTeller++;
            str = "T"+nomorAntrianTeller;
        }else{
            nomorAntrianCs++;
            str = "C"+nomorAntrianCs;
        }
        buf = str.getBytes();
        serversocket.send(new DatagramPacket(buf,str.length(), ia, cport));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdmin = new javax.swing.JButton();
        btnCs = new javax.swing.JButton();
        btnTeller = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdmin.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnAdmin.setText("LAYANAN ADMIN");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnCs.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnCs.setText("LAYANAN CS");
        btnCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCsActionPerformed(evt);
            }
        });

        btnTeller.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnTeller.setText("LAYANAN TELLER");
        btnTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTellerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTeller, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCs, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCs, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTeller, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        try {
            sendRequest("admin");
        } catch (UnknownHostException ex) {
            Logger.getLogger(KioskForm2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(KioskForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCsActionPerformed
        try {
            sendRequest("cs");
        } catch (UnknownHostException ex) {
            Logger.getLogger(KioskForm2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(KioskForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCsActionPerformed

    private void btnTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTellerActionPerformed
        try {
            sendRequest("teller");
        } catch (UnknownHostException ex) {
            Logger.getLogger(KioskForm2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(KioskForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTellerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KioskForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KioskForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KioskForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KioskForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KioskForm2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCs;
    private javax.swing.JButton btnTeller;
    // End of variables declaration//GEN-END:variables
}
